<?php

namespace ContainerXRDlDWw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EbXIZQUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EbXIZQU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EbXIZQU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cartManager' => ['privates', 'App\\Manager\\CartManager', 'getCartManagerService', true],
            'livres' => ['privates', '.errored..service_locator.EbXIZQU.App\\Entity\\Livres', NULL, 'Cannot autowire service ".service_locator.EbXIZQU": it references class "App\\Entity\\Livres" but no such service exists.'],
        ], [
            'cartManager' => 'App\\Manager\\CartManager',
            'livres' => 'App\\Entity\\Livres',
        ]);
    }
}
