<?php

namespace ContainerXRDlDWw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLivresService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator..Dm49sj.App\Entity\Livres' shared service.
     *
     * @return \App\Entity\Livres
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator..Dm49sj": it references class "App\\Entity\\Livres" but no such service exists.');
    }
}
