<?php

namespace ContainerXRDlDWw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRemoveExpiredCartsCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\RemoveExpiredCartsCommand' shared autowired service.
     *
     * @return \App\Command\RemoveExpiredCartsCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'RemoveExpiredCartsCommand.php';

        $container->privates['App\\Command\\RemoveExpiredCartsCommand'] = $instance = new \App\Command\RemoveExpiredCartsCommand();

        $instance->setName('app:remove-expired-carts');
        $instance->setDescription('Add a short description for your command');

        return $instance;
    }
}
