<?php

namespace ContainerEOlcxCL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__Dm49sjService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator..Dm49sj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..Dm49sj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'livre' => ['privates', '.errored..service_locator..Dm49sj.App\\Entity\\Livres', NULL, 'Cannot autowire service ".service_locator..Dm49sj": it references class "App\\Entity\\Livres" but no such service exists.'],
        ], [
            'livre' => 'App\\Entity\\Livres',
        ]);
    }
}
