<?php

namespace ContainerEOlcxCL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAddToCartTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\AddToCartType' shared autowired service.
     *
     * @return \App\Form\AddToCartType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\AddToCartType'] = new \App\Form\AddToCartType();
    }
}
