<?php

namespace ContainerEOlcxCL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCartTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\CartType' shared autowired service.
     *
     * @return \App\Form\CartType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\CartType'] = new \App\Form\CartType(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));
    }
}
