<?php

namespace ContainerEOlcxCL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLivres2Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.EbXIZQU.App\Entity\Livres' shared service.
     *
     * @return \App\Entity\Livres
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.EbXIZQU": it references class "App\\Entity\\Livres" but no such service exists.');
    }
}
