<?php

namespace ContainerEOlcxCL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderItemRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\OrderItemRepository' shared autowired service.
     *
     * @return \App\Repository\OrderItemRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\OrderItemRepository'] = new \App\Repository\OrderItemRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
