<?php

namespace ContainerEOlcxCL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRemoveExpiredCartsCommand_LazyService extends App_KernelProdContainer
{
    /*
     * Gets the private '.App\Command\RemoveExpiredCartsCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.App\\Command\\RemoveExpiredCartsCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:remove-expired-carts', [], 'Add a short description for your command', false, function () use ($container): \App\Command\RemoveExpiredCartsCommand {
            return ($container->privates['App\\Command\\RemoveExpiredCartsCommand'] ?? $container->load('getRemoveExpiredCartsCommandService'));
        });
    }
}
