<?php

namespace ContainerEOlcxCL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRemoveCartItemListenerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\EventListener\RemoveCartItemListener' shared autowired service.
     *
     * @return \App\Form\EventListener\RemoveCartItemListener
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService'));

        if (isset($container->privates['App\\Form\\EventListener\\RemoveCartItemListener'])) {
            return $container->privates['App\\Form\\EventListener\\RemoveCartItemListener'];
        }

        return $container->privates['App\\Form\\EventListener\\RemoveCartItemListener'] = new \App\Form\EventListener\RemoveCartItemListener($a);
    }
}
