<?php

namespace ContainerEOlcxCL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRemoveExpiredCartsCommandService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Command\RemoveExpiredCartsCommand' shared autowired service.
     *
     * @return \App\Command\RemoveExpiredCartsCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Command\\RemoveExpiredCartsCommand'] = $instance = new \App\Command\RemoveExpiredCartsCommand();

        $instance->setName('app:remove-expired-carts');
        $instance->setDescription('Add a short description for your command');

        return $instance;
    }
}
