<?php

namespace ContainerEOlcxCL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getValAuthenticatorService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Security\ValAuthenticator' shared autowired service.
     *
     * @return \App\Security\ValAuthenticator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Security\\ValAuthenticator'] = new \App\Security\ValAuthenticator(($container->services['router'] ?? $container->getRouterService()));
    }
}
