<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXRDlDWw\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXRDlDWw/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXRDlDWw.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXRDlDWw\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXRDlDWw\App_KernelDevDebugContainer([
    'container.build_hash' => 'XRDlDWw',
    'container.build_id' => '17fa29d0',
    'container.build_time' => 1674726519,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXRDlDWw');
